### ISSUE TITLE
GWC speed scalability improvements  

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#146]
- [x] Run some performance test to identify bottlenecks in various scenarios (when seeding, when serving, when truncating, when doing 2 of the above operations of all them at the same time, S3, Azure if possible)
- [ ] Optimize code that writes metadata for tiles
- [ ] The meta-tile tiles should be returned and stored asynchronously
- [ ] Better metatiling code
- [ ] Optimize tile size code

**Comment by simboss** [comment]
@aaime let me knoow what you think about it

**Comment by aaime** [comment]
Documents (not yet in any folder):
* Technical report: https://docs.google.com/document/d/1PVDrhocENbxlwRTGOcdq0pmEzlPnJJVFxnQs0CeQQ98/edit
* Tasks: https://docs.google.com/spreadsheets/d/1goNOZhgiXV8_UfZd474BCb6zOPy8EiERv2c_mRSFFeo/edit#gid=376642658

**Comment by simboss** [comment]
closed in favour of #404
