### ISSUE TITLE
Equi7Grid implementation and deployment

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/eumetsat-EOWS#346]
https://cgi-pathfinders.atlassian.net/browse/IMGMT-368

- [x] fixes in GeoServer (no speed improvements for the moment) #352 
- [x] test, deployment and configuration #353 
- [x] Update [wiki page about Eumetsat backports](https://github.com/geosolutions-it/eumetsat-EOWS/wiki/Eumetsat-Pathfinder-2019-2020)

**Comment by simboss** [comment]
information on branches and GeoServer versions [here](https://github.com/geosolutions-it/eumetsat-EOWS/wiki/Eumetsat-Pathfinder-2019-2020)

**Comment by randomorder** [comment]
done

**Comment by randomorder** [comment]
Waiting for validatio to deploy in OPE . See also #382

**Comment by randomorder** [comment]
GT improvements deployed in DEV. Waiting for feedback to move on to OPE

**Comment by randomorder** [comment]
Sent a MR for VAL waiting for feedback

**Comment by randomorder** [comment]
[deployed ](https://cgi-pathfinders.atlassian.net/browse/IMGMT-368)
